# Generated by scripts/generate_protocol.py. Do not edit.
from typing import Literal

PROTOCOL_VERSION = 2
ProtocolVersion = Literal[2]
EngineCommand = Literal[
    "automation",
    "cache",
    "commit",
    "doctor",
    "explain",
    "git_action",
    "hooks",
    "init",
    "panel_review",
    "pr_prepare",
    "provider",
    "providers",
    "review",
    "scan",
    "status",
    "workspace",
]
EngineEventName = Literal[
    "ready",
    "progress",
    "consent_required",
    "provider_delta",
    "finding",
    "job_update",
    "recovery_required",
    "scan_progress",
    "complete",
    "error",
]
ENGINE_COMMANDS = (
    "automation",
    "cache",
    "commit",
    "doctor",
    "explain",
    "git_action",
    "hooks",
    "init",
    "panel_review",
    "pr_prepare",
    "provider",
    "providers",
    "review",
    "scan",
    "status",
    "workspace",
)
ENGINE_EVENTS = (
    "ready",
    "progress",
    "consent_required",
    "provider_delta",
    "finding",
    "job_update",
    "recovery_required",
    "scan_progress",
    "complete",
    "error",
)
