# Generated by scripts/generate_protocol.py. Do not edit.
from typing import Literal

ProtocolVersion = Literal[4]
PROTOCOL_VERSION: ProtocolVersion = 4
EngineCommand = Literal[
    "automation",
    "cache",
    "commit",
    "doctor",
    "explain",
    "git_action",
    "hooks",
    "init",
    "panel_review",
    "pr_prepare",
    "provider",
    "providers",
    "review",
    "scan",
    "status",
    "workspace",
]
EngineEventName = Literal[
    "ready",
    "progress",
    "consent_required",
    "provider_delta",
    "finding",
    "job_update",
    "recovery_required",
    "scan_progress",
    "workflow_stage",
    "operation_started",
    "operation_completed",
    "operation_skipped",
    "readiness_changed",
    "complete",
    "error",
]
FindingSeverity = Literal[
    "critical",
    "high",
    "medium",
    "low",
]
FindingLifecycleState = Literal[
    "open",
    "needs_rereview",
    "resolved",
    "dismissed",
]
GitOperationRisk = Literal[
    "low",
    "medium",
    "high",
    "irreversible",
]
ENGINE_COMMANDS = (
    "automation",
    "cache",
    "commit",
    "doctor",
    "explain",
    "git_action",
    "hooks",
    "init",
    "panel_review",
    "pr_prepare",
    "provider",
    "providers",
    "review",
    "scan",
    "status",
    "workspace",
)
ENGINE_EVENTS = (
    "ready",
    "progress",
    "consent_required",
    "provider_delta",
    "finding",
    "job_update",
    "recovery_required",
    "scan_progress",
    "workflow_stage",
    "operation_started",
    "operation_completed",
    "operation_skipped",
    "readiness_changed",
    "complete",
    "error",
)
