# Generated by scripts/generate_protocol.py. Do not edit.
from typing import Literal

PROTOCOL_VERSION = 1
ProtocolVersion = Literal[1]
EngineCommand = Literal[
    "cache",
    "commit",
    "doctor",
    "explain",
    "hooks",
    "init",
    "panel_review",
    "pr_prepare",
    "providers",
    "review",
    "status",
]
EngineEventName = Literal[
    "ready",
    "progress",
    "consent_required",
    "provider_delta",
    "finding",
    "complete",
    "error",
]
ENGINE_COMMANDS = (
    "cache",
    "commit",
    "doctor",
    "explain",
    "hooks",
    "init",
    "panel_review",
    "pr_prepare",
    "providers",
    "review",
    "status",
)
ENGINE_EVENTS = (
    "ready",
    "progress",
    "consent_required",
    "provider_delta",
    "finding",
    "complete",
    "error",
)
