from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "protocol" / "schema.json"
TYPESCRIPT_OUTPUT = ROOT / "apps" / "cli" / "src" / "protocol.generated.ts"
PYTHON_OUTPUT = (
    ROOT / "engine" / "src" / "codepreflight_engine" / "protocol_generated.py"
)


def _lines(values: list[str], indent: str = "  ") -> str:
    return "\n".join(f"{indent}{json.dumps(value)}," for value in values)


def render() -> dict[Path, str]:
    schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
    request = schema["$defs"]["request"]["properties"]
    event = schema["$defs"]["event"]["properties"]
    version = int(request["protocolVersion"]["const"])
    commands = list(request["command"]["enum"])
    events = list(event["event"]["enum"])
    severities = list(schema["$defs"]["severity"]["enum"])
    lifecycles = list(schema["$defs"]["findingLifecycle"]["enum"])
    git_risks = list(schema["$defs"]["gitRisk"]["enum"])
    typescript = f"""// Generated by scripts/generate_protocol.py. Do not edit.
export const PROTOCOL_VERSION = {version} as const;
export const ENGINE_COMMANDS = [
{_lines(commands)}
] as const;
export type EngineCommand = (typeof ENGINE_COMMANDS)[number];
export const ENGINE_EVENTS = [
{_lines(events)}
] as const;
export type EngineEventName = (typeof ENGINE_EVENTS)[number];
export const FINDING_SEVERITIES = [
{_lines(severities)}
] as const;
export type FindingSeverity = (typeof FINDING_SEVERITIES)[number];
export const FINDING_LIFECYCLE_STATES = [
{_lines(lifecycles)}
] as const;
export type FindingLifecycleState = (typeof FINDING_LIFECYCLE_STATES)[number];
export const GIT_OPERATION_RISK_LEVELS = [
{_lines(git_risks)}
] as const;
export type GitOperationRisk = (typeof GIT_OPERATION_RISK_LEVELS)[number];
"""
    python = f"""# Generated by scripts/generate_protocol.py. Do not edit.
from typing import Literal

ProtocolVersion = Literal[{version}]
PROTOCOL_VERSION: ProtocolVersion = {version}
EngineCommand = Literal[
{_lines(commands, "    ")}
]
EngineEventName = Literal[
{_lines(events, "    ")}
]
FindingSeverity = Literal[
{_lines(severities, "    ")}
]
FindingLifecycleState = Literal[
{_lines(lifecycles, "    ")}
]
GitOperationRisk = Literal[
{_lines(git_risks, "    ")}
]
ENGINE_COMMANDS = (
{_lines(commands, "    ")}
)
ENGINE_EVENTS = (
{_lines(events, "    ")}
)
"""
    return {TYPESCRIPT_OUTPUT: typescript, PYTHON_OUTPUT: python}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    options = parser.parse_args()
    stale: list[Path] = []
    for path, expected in render().items():
        if options.check:
            if not path.exists() or path.read_text(encoding="utf-8") != expected:
                stale.append(path.relative_to(ROOT))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8")
    if stale:
        print("Generated protocol artifacts are stale:")
        for path in stale:
            print(f"- {path}")
        print("Run: npm run protocol:generate")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
