// Generated by scripts/generate_protocol.py. Do not edit.
export const PROTOCOL_VERSION = 3 as const;
export const ENGINE_COMMANDS = [
  "automation",
  "cache",
  "commit",
  "doctor",
  "explain",
  "git_action",
  "hooks",
  "init",
  "panel_review",
  "pr_prepare",
  "provider",
  "providers",
  "review",
  "scan",
  "status",
  "workspace",
] as const;
export type EngineCommand = (typeof ENGINE_COMMANDS)[number];
export const ENGINE_EVENTS = [
  "ready",
  "progress",
  "consent_required",
  "provider_delta",
  "finding",
  "job_update",
  "recovery_required",
  "scan_progress",
  "workflow_stage",
  "operation_started",
  "operation_completed",
  "operation_skipped",
  "readiness_changed",
  "complete",
  "error",
] as const;
export type EngineEventName = (typeof ENGINE_EVENTS)[number];
