// Generated by scripts/generate_protocol.py. Do not edit.
export const PROTOCOL_VERSION = 4 as const;
export const ENGINE_COMMANDS = [
  "automation",
  "cache",
  "commit",
  "doctor",
  "explain",
  "git_action",
  "hooks",
  "init",
  "panel_review",
  "pr_prepare",
  "provider",
  "providers",
  "review",
  "scan",
  "status",
  "workspace",
] as const;
export type EngineCommand = (typeof ENGINE_COMMANDS)[number];
export const ENGINE_EVENTS = [
  "ready",
  "progress",
  "consent_required",
  "provider_delta",
  "finding",
  "job_update",
  "recovery_required",
  "scan_progress",
  "workflow_stage",
  "operation_started",
  "operation_completed",
  "operation_skipped",
  "readiness_changed",
  "complete",
  "error",
] as const;
export type EngineEventName = (typeof ENGINE_EVENTS)[number];
export const FINDING_SEVERITIES = [
  "critical",
  "high",
  "medium",
  "low",
] as const;
export type FindingSeverity = (typeof FINDING_SEVERITIES)[number];
export const FINDING_LIFECYCLE_STATES = [
  "open",
  "needs_rereview",
  "resolved",
  "dismissed",
] as const;
export type FindingLifecycleState = (typeof FINDING_LIFECYCLE_STATES)[number];
export const GIT_OPERATION_RISK_LEVELS = [
  "low",
  "medium",
  "high",
  "irreversible",
] as const;
export type GitOperationRisk = (typeof GIT_OPERATION_RISK_LEVELS)[number];
