// Generated by scripts/generate_protocol.py. Do not edit.
export const PROTOCOL_VERSION = 1 as const;
export const ENGINE_COMMANDS = [
  "cache",
  "commit",
  "doctor",
  "explain",
  "hooks",
  "init",
  "panel_review",
  "pr_prepare",
  "providers",
  "review",
  "status",
] as const;
export type EngineCommand = (typeof ENGINE_COMMANDS)[number];
export const ENGINE_EVENTS = [
  "ready",
  "progress",
  "consent_required",
  "provider_delta",
  "finding",
  "complete",
  "error",
] as const;
export type EngineEventName = (typeof ENGINE_EVENTS)[number];
